-- Add migration script here
ALTER TABLE tokens
ADD COLUMN price_change_24h_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN volume_24h_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN discord_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN twitter_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN website_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN telegram_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN decimals INTEGER NOT NULL DEFAULT 0;